"""

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        hash_table = {

        }

        for i in s:
            if i in hash_table:
                hash_table[i] += 1

            else:
                hash_table[i] = 1


        for j in t:
            if j not in hash_table:
                return j 

            hash_table[j] -= 1

            if hash_table[j] < 0:
                return j


a1 = Solution()
print(a1.findTheDifference("abcd" , "abcde"))